server:
  port: 8080

spring:
  # 数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://172.38.0.3:3306/steam_edu?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "nfsn520"
    type: com.alibaba.druid.pool.DruidDataSource             # 当前数据源操作类型
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    cluster:
      nodes: 172.38.0.11:6379,172.38.0.12:6379,172.38.0.13:6379 # Redis集群节点
      max-redirects: 3  # 最大重定向数，建议设置为3
    timeout: 3000  # Redis连接超时时间，单位毫秒
    jedis:
      pool:
        max-idle: 100
        max-wait: 1
#alipay:
#  appId: 2021000121637995 #需要自己的appID
#  privateKey: xxxx #支付的私钥
#  publicKey: xxx #支付的私钥
#  notifyUrl: http://localhost:8090
#  returnUrl: http://localhost:8090/alipay
#  signType: RSA2
#  charset: utf-8
#  gatewayUrl: https://openapi.alipaydev.com/gateway.do #此处使用的是沙箱环境的支付宝网关
#  logPath: "E:\\alipay.log"
#
#mybatis-plus:
#  global-config:
#    db-config:
#      id-type: auto
#file-save-path: A:/uploadFile/          #文件路径