server:
  port: 8090

spring:
  # 数据库相关
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/steam_edu?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: xxx
    type: com.alibaba.druid.pool.DruidDataSource             # 当前数据源操作类型
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: xxx
    port: 6379
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 8   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间
alipay:
  appId: 2021000121637995 #需要自己的appID
  privateKey: xxxx #支付的私钥
  publicKey: xxx #支付的私钥
  notifyUrl: http://localhost:8090
  returnUrl: http://localhost:8090/alipay
  signType: RSA2
  charset: utf-8
  gatewayUrl: https://openapi.alipaydev.com/gateway.do #此处使用的是沙箱环境的支付宝网关
  logPath: "E:\\alipay.log"

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
file-save-path: A:/uploadFile/          #文件路径