# Server configuration
server:
  port: 8080

# Spring configuration
spring:
  # Database configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver                      # MySQL driver package
    url: jdbc:mysql://47.120.32.32:3306/steam_edu?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: "nfsn520"
    type: com.alibaba.druid.pool.DruidDataSource                      # Current data source operation type

  # Swagger related
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # Redis related
  redis:
    host: 47.120.32.32
    port: 6371
    password: nfsn-redis-6371
    lettuce:
      pool:
        max-active: 8  #最大连接
        max-idle: 100   #最大空闲连接
        min-idle: 0   #最小空闲连接
        max-wait: 100ms #连接等待时间
  #    cluster:
#      nodes: 172.38.0.11:6379,172.38.0.12:6379,172.38.0.13:6379       # Redis cluster nodes
#      max-redirects: 3                                                # Maximum number of redirects, recommended to set to 3
#    timeout: 3000                                                     # Redis connection timeout, in milliseconds
#    jedis:
#      pool:
#        max-idle: 100
#        max-wait: 1
  servlet:                                                   # servlet properties
    multipart:                                               # multipart properties
      max-file-size: 200MB                                   # maximum file size for multipart request
      max-request-size: 200MB                                # maximum request size for multipart request

# MinIO configuration
minio:
  endpoint: http://47.120.32.32:9000
  access-Key: IWgSXNvJz86GuK3A
  secret-Key: ACwg1tjrAMoIQGSoqdeoyqhmzUVvckhp

app:
  update:
    latestVersion: 2.0.0
    downloadUrl: https://example.com/app/download/app_v2.0.0.apk

#alipay:
#  appId: 2021000121637995 #需要自己的appID
#  privateKey: xxxx #支付的私钥
#  publicKey: xxx #支付的私钥
#  notifyUrl: http://localhost:8090
#  returnUrl: http://localhost:8090/alipay
#  signType: RSA2
#  charset: utf-8
#  gatewayUrl: https://openapi.alipaydev.com/gateway.do #此处使用的是沙箱环境的支付宝网关
#  logPath: "E:\\alipay.log"
#
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
#file-save-path: A:/uploadFile/          #文件路径